### ISSUE TITLE
Problem with pip-egg-info?

### ISSUE THREAD

**Issue by tschm** [MOSEK/Mosek.pip#1]
Hi Ulf, 
I am running Ubuntu 64 bit. I build a local environment (based on Python 2.7.6) and then run

pip install git+http://github.com/MOSEK/Mosek.pip

I get this error message...

Downloading/unpacking git+http://github.com/MOSEK/Mosek.pip
  Cloning http://github.com/MOSEK/Mosek.pip to /tmp/pip-CFPh4_-build
  Running setup.py (path:/tmp/pip-CFPh4_-build/setup.py) egg_info for package from git+http://github.com/MOSEK/Mosek.pip
    Fetching http://download.mosek.com/stable/7/mosektoolslinux64x86.tar.bz2 -> /home/thomas/Downloads/ff086e513893757bea1076328bfdb130f5de3c384377bb759db3062e9731f0a6e80bbee19d47dc5923dffad07fc205df1daf0aedae62f1469642f935a629f38c_mosektoolslinux64x86.tar.bz2
    OK
    Unpacking...
    OK
    error: error in 'egg_base' option: 'pip-egg-info' does not exist or is not a directory

**Comment by ulfworsoe** [comment]
I can reproduce the problem. An error is reported, but the installation seems to work anyway. 
I suspect that it has something to do with the way I call `setup.py` in the distribution.

**Comment by ulfworsoe** [comment]
I think the issue has been fixed: The installation procedure has been completely rewritten, so it no longer uses the `setup.py` in the MOSEK distro.
