### ISSUE TITLE
mosek for python 2.7

### ISSUE THREAD

**Issue by yanzhipingliu** [MOSEK/Mosek.pip#10]
I tried to install mosek for python through the following directory 
C:\Program Files (x86)\Mosek\8\tools\platform\win32x86\python\2
but the setup.py does not work

it says keyerror: win32*86

**Comment by ulfworsoe** [comment]
Hi,

This is not a PIP issue but a MOSEK installer issue.

I can't immediately reproduce the error. Can I ask you to send to support@mosek.com:
- Mosek version number
- Python build info (the text printed when you start the interactive python shell)
- The full output from running `setup.py`
