### ISSUE TITLE
Mosek.pip for 7.0.0.141

### ISSUE THREAD

**Issue by nimish** [MOSEK/Mosek.pip#15]
How do install Mosek python3 libraries for 7.0.0.141 specifically? There doesn't seem to be a versioned release, but the setup.py seems to support 7.0 releases.

**Comment by ulfworsoe** [comment]
Hi,

No, we did not have versioned releases at version 7.0. 

I have add a 7.0 branch and a tag for 7.0.141 that you can try to install from. If it does not work, please post the output of the failing command here.

**Comment by nimish** [comment]
@ulfworsoe works for me!
