### ISSUE TITLE
Wheels and custom PyPI

### ISSUE THREAD

**Issue by nimish** [MOSEK/Mosek.pip#16]
Hi,

It looks like wheels for each supported platform would be better than the current method of unpacking a tar.gz on build. I can construct one using bdist_wheel, but it's missing the right metadata on platform and ABI, and would be a lot easier if they were pre-constructed somewhere, since the code is already compiled.

**Comment by ulfworsoe** [comment]
Hi,

I perfectly agree. The current method leaves a lot to be desired, and in fact we have Conda packages (with prebuilt binaries, much like wheels). I am at the moment investigating if wheels are an option - as usual this is more about license-conflicts than about technical problems.

**Comment by nimish** [comment]
Yes, I doubt that the regular PyPI would like the existing license, but it would make a lot of sense to have a custom "pypi.mosek.com" for licensees. Just food for thought :)

**Comment by ulfworsoe** [comment]
I have made some experiments with Wheels. It seems that wheels have no way to handle shared library dependencies (in our case we rely on the solver library and a threading library). 
I will look into hosting packages, but unless i find a way around the library problem it may have to be a `setup.py` bases installer.

**Comment by nimish** [comment]
@ulfworsoe Hmm, that's going to be difficult...the only solution i know of, and only for linux, is https://pypi.python.org/pypi/auditwheel

Other options are using CFFI and having the shared libs be included

**Comment by nimish** [comment]
Mostly addressed by https://github.com/MOSEK/Mosek.pip/pull/19 ; wheels do not have the correct platform info, but changing that would need some changes in the core mosek python code.
