### ISSUE TITLE
please add up the proxy setting when download the newest mosek in setup.py

### ISSUE THREAD

**Issue by CharlesLiu7** [MOSEK/Mosek.pip#17]
For some reason my computer must connect the network with proxy, when I use the command 
`pip install --user git+http://github.com/MOSEK/Mosek.pip --proxy=http://...`, the code prints out
```
running install
    running build
    Fetch and unpack MOSEK distro
    error: <urlopen error>
```
In my opinion, the setup.py doesn't add a proxy when `pip` uses the proxy.
Can you add up the proxy setting?

**Comment by ulfworsoe** [comment]
Unfortunately, I don't think it is that easy. The `--proxy` argument is not passed from PIP to the `setup.py ` script where MOSEK is downloaded. I'll keep the ticket open and see if I can work around it somehow. In the meantime, your options are:
- Either download and unpack the relevant MOSEK distro, and run `setup.py` from there, or
- Use anaconda (with `conda install -s mosek mosek`)

**Comment by nimish** [comment]
Should be addressed in https://github.com/MOSEK/Mosek.pip/pull/19 by using urlretrieve even on python 2
