### ISSUE TITLE
Cannot install with pip in python 3.5 from ubuntu nor python 3.6.3 with pyenv

### ISSUE THREAD

**Issue by IgnacioRubioScola** [MOSEK/Mosek.pip#20]
I have python 3.5.3 from Ubuntu and python 3.6.3 from pyenv, when i try to install mosek with pip:
`pip install git+http://github.com/MOSEK/Mosek.pip`
I get the following error in both cases

>File "/tmp/pip-jshp5j5m-build/setup.py", line 214, in _pre_install
>pypfx = '{0}/python/{1}/mosek'.format(distroplatformpfx, major)
>NameError: name 'major' is not defined

**Comment by ulfworsoe** [comment]
A bug was introduced earlier today. Should be fixed now - please try again.
