### ISSUE TITLE
the mosek version installed via `pip install`  doesn't sync well with `conda install -c mosek mosek` 

### ISSUE THREAD

**Issue by taoluo** [MOSEK/Mosek.pip#21]
I have to use pip to prepare the python environment. Sadly I encountered some issues with pip installed version which is 8.1.30. the same version installed by conda has no problems.
the error raised is:
```
AttributeError: Task instance has no attribute '_Task__library'
```
Any hint on installing Mosek correctly via pip?

**Comment by ulfworsoe** [comment]
Hi,
We have had some serious issues keeping the Mosek.PIP package updated and working. We are in the process of switching to Wheels based packaging. I expect that a mosek Wheels repository that can be used with PIP will be online within a few days.

**Comment by ulfworsoe** [comment]
Hi,

If it is still relevant for you: We have created binary Wheel packages for Mosek. It is not documented yet, but following installs mosek using PIP:

```
pip install -f http://download.mosek.com/stable/wheel/index.html Mosek
```
It should work for Windows and Linux. There is currently an issue with OS X, but that will be fixed in next build. 

Any feedback is welcome.

**Comment by taoluo** [comment]
Great！I am going to run my test code against this wheel version.
