### ISSUE TITLE
Python 3.7 Support

### ISSUE THREAD

**Issue by AkaP88** [MOSEK/Mosek.pip#22]
Hello,

Is there a Mosek binary for Python 3.7/Win64 or it is not yet available ?

Binaries on Conda seems to be recent (5 days ago) but support of Py3.7 is not there.

Thanks!

**Comment by ulfworsoe** [comment]
Hi,

I can see we have not yet added the packages for Python 3.7. I'll look into it.

**Comment by AkaP88** [comment]
Thanks a lot!

**Comment by ulfworsoe** [comment]
I am having some issues getting the 3.7 build to work. It may not be available until next week.

**Comment by AkaP88** [comment]
Thanks a lot. Looking forward to it!

**Comment by ulfworsoe** [comment]
I am sorry this took so long, but there were some complications. A new build is online that should support Python3.7. The anaconda packages have also been update.
