### ISSUE TITLE
Fusion in Python 3

### ISSUE THREAD

**Issue by tschm** [MOSEK/Mosek.pip#3]
Hi Ulf,
you mentioned Fusion is not ready for Python 3. Are there any plans to make this possible, too?
I wish Fusion would be a bit less forgiving. E.g. I think there is potential to make it faster by only accepting numpy arrays and ditch standard python lists as arguments. Using that way you might have less complexity in feeding into C code. 
Would that work?
Thomas

**Comment by ulfworsoe** [comment]
Mosek 8.0 will support Fusion for both Python 2 and 3, and it will use NumPy arrays as the native array type (this means that it will only work with numpy installed). It will still accept Python lists, but internally they are converted into numpy arrays. 
I believe that it makes Fusion a bit faster, but I have no concrete numbers; I have made a lot of other improvements so it is hard to isolate the effect of switching to numpy.

**Comment by ulfworsoe** [comment]
And I should mention: Python 3 appears consistently to be slightly slower that Python 2 ( around 5%), probably because of integer arithmetics.

**Comment by tschm** [comment]
Can you please comment on the expected release date of Mosek 8?
thomas

**Comment by ulfworsoe** [comment]
I think that it currently looks like sometime this fall. Erling hasn't set an official deadline yet.

**Comment by tschm** [comment]
Happy new year Ulf. What's the latest greatest news on Mosek 8?

**Comment by ulfworsoe** [comment]
Hi, and happy New Year to you too!

I am afraid that I cannot say anything definite (not because I won't, but
because I don't know).

Another thing you might be interested in is that we are working on an
Anaconda package, which should be official before too long.

On Mon, Jan 4, 2016 at 2:42 PM, Thomas Schmelzer notifications@github.com
wrote:

> Happy new year Ulf. What's the latest greatest news on Mosek 8?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MOSEK/Mosek.pip/issues/3#issuecomment-168678791.

## 

Ulf Worsøe
Mosek ApS

ulf.worsoe@mosek.com
www.mosek.com

**Comment by ulfworsoe** [comment]
Since v8.0 Python 3 is supported, and the anaconda package are live.
