### ISSUE TITLE
Please make releases

### ISSUE THREAD

**Issue by tschm** [MOSEK/Mosek.pip#4]
Hi Ulf,
it's a good idea to make releases (e.g. tags) in your github rep. This way I can avoid pointing to your more dynamic master branch. Adds stability. 
thomas

**Comment by ulfworsoe** [comment]
Hi,

You are perfectly right. Currently it is not a big problem, but it may
become an issue when version 8 comes out. I'll take a look at it.

On Wed, Sep 16, 2015 at 11:36 AM, Thomas Schmelzer <notifications@github.com

> wrote:
> 
> Hi Ulf,
> it's a good idea to make releases (e.g. tags) in your github rep. This way
> I can avoid pointing to your more dynamic master branch. Adds stability.
> thomas
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MOSEK/Mosek.pip/issues/4.

## 

Ulf Worsøe
Mosek ApS

ulf.worsoe@mosek.com
www.mosek.com

**Comment by ulfworsoe** [comment]
I have added a v7.0.0 release. When  Mosek 8.0 is out I will maintain a MOSEK 7 installer using v7.x tags and the MOSEK 8 installer using v8.x tags.
