### ISSUE TITLE
Build for Windows messed up?

### ISSUE THREAD

**Issue by tschm** [MOSEK/Mosek.pip#6]
C:\Users\Thomas\Dropbox\github\pyopt>env\python
Python 2.7.10 |Continuum Analytics, Inc.| (default, Sep 15 2015, 14:26:14) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

> > > import mosek
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Users\Thomas\Dropbox\github\pyopt\env\lib\site-packages\mosek__init__.py", line 639, in <module>
> > >     raise ImportError('Failed to import dll "%s"' % **libname)
> > > ImportError: Failed to import dll "##<libname>.dll"
> > > import mosek.fusion
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Users\Thomas\Dropbox\github\pyopt\env\lib\site-packages\mosek__init**.py", line 39, in <module>
> > >     from mosek import array
> > > ImportError: cannot import name array

Hi Ulf, the recent changes seem to have a negative impact on my Windows Box. I didn't observer similar problems on the Linux box. Can you please have a look.

**Comment by ulfworsoe** [comment]
Oh no. I know exactly what this is... An artifact of out build system being run with an older version of Python. I will fix it tomorrow.

**Comment by tschm** [comment]
I see. I run with Python 2.7.10 (as Fusion wouldn't work on Python 3). So the version isn't that old :-)
Btw:
I would write "Failed to import dll {0}".format(libname). I haven'^t seen your ##<> constructs before... Is that some magic trick I am not aware of?

**Comment by ulfworsoe** [comment]
No trick, just a substitution bug. I think a new distro should be online.

**Comment by tschm** [comment]
I see no difference at this stage. How do I make sure that I pull a fresh download rather than an old version stored on my drive?

**Comment by ulfworsoe** [comment]
Please try again now. I have checked that the newly oploaded version is
correct (or at least that particular bug has been fixed).

On Wed, Oct 7, 2015 at 11:12 PM, Thomas Schmelzer notifications@github.com
wrote:

> I see no difference at this stage. How do I make sure that I pull a fresh
> download rather than an old version stored on my drive?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MOSEK/Mosek.pip/issues/6#issuecomment-146330753.

## 

Ulf Worsøe
Mosek ApS

ulf.worsoe@mosek.com
www.mosek.com

**Comment by tschm** [comment]
Works. Many thanks!
