### ISSUE TITLE
Installation on Linux

### ISSUE THREAD

**Issue by PkuClosed** [MOSEK/Mosek.pip#7]
Hi,

I am using conda to install mosek: "conda install -c mosek mosek=8.0.46". After installation, when I imported mosek, I got the following error: "Failed to import dll "libmosekxx7_1.so"". I am wondering if there is anything I can do about it.

Thank you in advance.

**Comment by ulfworsoe** [comment]
Hi,

The conda installer does not install the PIP Package but a Conda package. 

In any case: It appears to work for me. Is it possible that you have an old MOSEK installed somewhere that gets picked up? You can (assuming you are using python 2.7) to check if `mosek` is installed in
```
$HOME/.local/lib/python2.7/site-packages
```
If it is, you can simply delete the directories `mosek` and `Mosek-*` to get rid of an old Mosek installation.

If this doesn't solve the problem or you have further issues, please write to support@mosek.com.
