### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by stephane-caron** [MOSEK/Mosek.pip#8]
Hi there,

There seems to be a problem with the version regexp in the ``setup.py`` script:

```
Downloading/unpacking git+http://github.com/MOSEK/Mosek.pip
  Cloning http://github.com/MOSEK/Mosek.pip to /tmp/pip-ahj_1k-build
  Running setup.py (path:/tmp/pip-ahj_1k-build/setup.py) egg_info for package from git+http://github.com/MOSEK/Mosek.pip
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-ahj_1k-build/setup.py", line 37, in <module>
        raise VersionError('No version entry in PKG-INFO')
    __main__.VersionError: No version entry in PKG-INFO
```

**Comment by tschm** [comment]
Did you know that you could install Mosek via conda...
conda install -y -q -c mosek mosek

**Comment by stephane-caron** [comment]
OK, I can try that.
But then I would install the whole package manager for just one package...
I'd prefer if the pip install worked ;)

**Comment by ulfworsoe** [comment]
The installer should work now. The Version number was not being correctly parsed.
